### ISSUE TITLE
Add support for using the library from C++

### ISSUE THREAD

**Issue by lpapp** [Orc/discount#113]
The code seems to have been designed with C in mind, but with a little extra effort, the general old 'extern "C"' practice could be applied in the library to make it usable in a C++ project off-hand.

**Comment by binki** [comment]
IMO, discount is a C API. It’s the responsibility of C++ developers to wrap inclusions of a C API’s headers in

    extern "C" {
    #include <mkdio.h>
    }

It should not be the responsibility of the C library. It’s a C library after all, not a C++ library…

But, it would probably be useful if someone created a C++ wrapper around `MMIOT *` that provided RAII behavior. Then the README could just refer C++ users to that wrapper and avoid creation of issues like this one perhaps?

**Comment by Orc** [comment]
Revisiting this after a couple of year;  I've fabricated a [c++ class](https://gist.github.com/Orc/97b5711dd8c8a3b371928db756eba6e5#file-stdio-h-L9) to wrap around it (MKIOT/GFIOT instead of MMIOT/GFIOT because clang c++ bitches about a c++ class name being the same as an embedded c typedef name) and tucked it into a gist for playing with.   Since I don't use c++, I don't know if I can exhaustively test it, but if people play around with it and it actually works for them I'll collapse it into the baseline sccs.

gist: https://gist.github.com/Orc/97b5711dd8c8a3b371928db756eba6e5#file-stdio-h-L9

**Comment by Orc** [comment]
I tweaked the gist a little bit, then wrote an *absolutely trivial* c++ program that uses it, and it worked.

~~~
#include <stdio.h>
#include "mkdio.h++"

int main(int argc, char **argv)
{
    FILE *foo = fopen("/tmp/bar.text", "r");

    if ( foo ) {
	MKIOT blob(foo, 0);

	blob.format(stdout, 0);
    }
    return 0;
}
~~~

(Alas, I couldn't find a way to overlay a c++ class name with a c typedef, so MKIOT it was.)

No exception throwing, no nothing. 

I annotated the test program with the osx command line I used to compile it and shoved it into the gist.
