### ISSUE TITLE
non breaking spaces and non breaking hyphens

### ISSUE THREAD

**Issue by dergraph** [Orc/discount#119]
for a non breaking space:
after spending a while on trying to get it to work via escaping using the slash ('\')
it seems to me that it simply is not supported.

for non breaking hyphens I have looked up a glyph that is not available via default keyboard shortcuts on  mac os atleast. however it is being compiled as desired…

i believe there should be a specific markdown expression such cases…

**Comment by Orc** [comment]
Discount (and, as far as I can tell, standard markdown) don't have any support for nonbreaking spaces or hyphens.   How are you needing them?

**Comment by davidfstr** [comment]
Wouldn't `&nbsp;` work to insert a non-breaking space?

**Comment by davidfstr** [comment]
Any for non-breaking hyphen in HTML, try `&#8209;`, as per the following StackOverview post:
http://stackoverflow.com/questions/7691569/no-line-break-after-a-hyphen

**Comment by Orc** [comment]
Yup, both of those work;   there's no language feature for markdown to do it natively, which I think dergraph was asking?

**Comment by dergraph** [comment]
well as a copy writer u sometimes use terms like say: ad-blocker 
or write a combination of a few words in quotes: "two words" 
these things should never break apart on a line ending.

and yes im referring to a markdown native way of doing so.
as u have en das em dash and things like that. why not have nonbreaking available somehow to for hyphens. or non breaking space more conveniently than escaping via slash. 

im using codekit to compile the md files which uses discount. 
maybe im doing something wrong but escaping doesnt seem to do the trick for spaces…

**Comment by Orc** [comment]
What sort of markup do you have in mind?

**Comment by dergraph** [comment]
I am not sure, I hoped you might have suggestions

what about:
-/- non breaking hyphen
_/_ non breaking space

**Comment by Orc** [comment]
How frequently do you need no have non-breaking space/hypen?    If it doesn't have to happen often a pseudo-protocol may be the way to go (`[ad-blocker](break:no)` or `["quoted string"](break:no)`) ?

**Comment by dergraph** [comment]
the non breaking hyphen is used extremely offen. the space not as often.

still it would be best if the syntax is intuitiv
since the copy writers that are not nessacarly tech savy.

**Comment by klick-barakgall** [comment]
+1, I actually can't imagine a use case where you would want a line to break on a dash, unless you're inserting a shy-hyphen somewhere (which makes no sense for a markdown document unless it literally is a shy-hyphen character that only appears in appropriate resolutions).

But I would challenge that in most/all markdown files a dash is ALWAYS non-breaking.

I'm not sure what the best method for nbsp would be. That's an interesting problem to allow for two separate whitespaces that are intuitive for copy writers considering most editors copywriters use would not have a way of delineating different types of spaces.

**Comment by Orc** [comment]
In a situation where there are only a few things that need to have nonbreaking spacing, there's always the raw: pseudo-protocol.

So something like

~~~~
[ad block]: raw:ad&nbsp;block
~~~~

and later in the document you'd write

~~~~
blah blah blah blah blah [ad block] blah blah blah
~~~~

to generate
~~~~
<p>blah blah blah blah blah ad&nbsp;block blah blah blah</p>
~~~~

(similarly for hyphens it would be `[ad-block]: raw:ad&#8209;block`)

**Comment by aidantwoods** [comment]
Hi there, I was just wondering whether anyone involved in this discussion had any ideas for a good syntax to use for non-breaking spaces – I was considering implementing something similar as a configurable option in a parser I'm working on, and this was one of the only two discussions I could find that talked about introducing new syntax for it. 

`\•` crops up as a suggestion in the discussion over on the CommonMark forums too, though there were some objections to it (personally I don't think it's that nice to look at.

The first thing that came to mind for me was to use a double space `••` as a npsp, it would look a lot nicer IMO, while still being *fairly* easy to spot if it was accidentally inserted and causing difficulty. Also, double space is meaningless in HTML at present, so there would be no lost functionality. Only thing I thought might be an issue, is that there's an old typewriter era convention to double space after a period (quick Google seems to indicate that it's frowned upon now, but I may be wrong).

As far as non-breaking hyphens go, perhaps an idea to allow both types would be to make all intra-word hyphens non-breaking, and keep the rest as-is?

**Comment by Orc** [comment]
I don't pay any attention to the commonmark forums, so I can't speak to what they're considering, but if you're going to do some non-ascii escape sequence like '\•' for a nonbreaking space, why not just '&nbsp;' and be done with it?   (Ditto for '••', unless you mean actual double space?   If you mean actual double space, that would be bad because many people still use double space after punctuation despite it being considered déclassé by people who still haven't emotionally realized that we're living in an era with basically infinite disk space for text documents.)

**Comment by aidantwoods** [comment]
> If you mean actual double space, that would be bad because many people still use double space after punctuation 

Yeah, so I would have been talking about an actual double space (using `•` to represent a space here because they get trimmed out of code spans).

> despite it being considered déclassé by people who still haven't emotionally realized that we're living in an era with basically infinite disk space for text documents.)

Ha, yeah. I don't personally have anything against using double spaces in that way. I just wondered whether, if it was a retired convention, then the double space might be safely used for something else.

But if people are double spacing after punctuation, that's a situation that they're likely to actually want a breaking space, so double space will not be a good syntax for nbsp if that's the case.

---

I think I will go ahead with making a feature for intra-word hyphens to be non-breaking (possibly with the option to force a regular hyphen, or maybe a shy-hyphen with `\-`) and have hyphens that have non-alphanumerics on any side be regular.

I'll have to have a think about the best syntax for nbsp though, and whether it's worth doing: on some OSs it's pretty accessible with a keyboard shortcut (Windows version is quite contrived though).

**Comment by clstmbrly** [comment]
For a nonbreaking space, I've found that &nbsp; (HTML) works just fine in GitHub Markdown; however, &#8209 did not work for a nonbreaking hyphen.

**Comment by clstmbrly** [comment]
Interesting that commenting doesn't allow "&nbsp;" to appear.  Perhaps the quotation marks will help.

**Comment by clstmbrly** [comment]
Strange.  Sorry folks.  The HTML for nonbreaking space is "ampersand n b s p semicolon" (with no spaces).

**Comment by Orc** [comment]
When you wrote `&#8209`, did you mean to leave the trailing ; off?   (backquote to escape)

**Comment by clstmbrly** [comment]
The internet source where I found the HTML for nonbreaking hyphen did not have a semicolon at the end.  Thanks so much!

**Comment by DOFfactory** [comment]
what about using as a non-breaking space the tilde from latex `~`?
