### ISSUE TITLE
Add support for GitHub style checkboxes

### ISSUE THREAD

**Issue by doup** [Orc/discount#142]
In GitHub there is the option to define TODO lists in this format:

```
- [ ] foo
- [X] bar
```

It would be nice to render the brackets like checkboxes. [See this gist](https://gist.github.com/doup/848aebd5131e1ff76cd2) to see how it's rendered in GitHub.

**Comment by Orc** [comment]
That's an amazingly hideous format.   I suppose the markdown parser GitHub uses doesn't support it so they run lists through a postprocessing stage to tweak it into shape (and that's not even considering that it clashes with lazy link syntax)?

**Comment by doup** [comment]
Hehe, then I suppose that's a no. I don't know how GitHub does it, but postprocessing definitely it's a solution for the `qlmarkdown` issue. Close this if you see it doesn't fit here.

**Comment by Orc** [comment]
If someone can provide me with a patch for this, I'd love to try and integrate it in.   What does the rendered html look like -- it may be doable with minimal side-effects (if the existance of a `- [ ]` forces wrapping the entire list in a form, it gets more difficult because the first stage would be the one that has to recognize the special `- [ ]` list item prefix and push a PLEASE FORM ME flag into the parent `<ul>` node so generate can spit out the necessary wrapper.

**Comment by Orc** [comment]
I dug through the gist for it, and the pretty github formatting of this requires classification.  Just the plain html (which is what discount would generate unless the checklist was wrapped in a `>%style%` box) would look like a list item marker, then a checkbox, then the label.    (I can't actually show this on github, because all of the generated html here is encrusted with style information, so unstyled checkboxes in lists look like:

<ul>
<li><input type="checkbox" checked="" disabled=""> foo</li>
<li><input type="checkbox" disabled=""> bar</li>
</ul>

... if there's a checkbox in there, I can't see it from Safari.)

I'd take a patch for this --  it looks like all you'd need to do is go into `listdisplay()` [in `generate.c` at ~line 1740] and check before each `htmlify()` for a '[]' or '[X]' pattern, spit out the `<input type`...`/>` string, and then trim the beginning of the line back so that the pattern won't then be parsed as whatever sort of thing it is when `htmlify()` is called -- but without a collection of styles to first disable the item marker, then reenable it unless there's a checkbox input immediately following it won't be very attractive.

So I don't think I'm going to implement this myself, and I'll close the request but accept patches if someone else wants to do the lifting.
