### ISSUE TITLE
Muñoz test fails on architectures where char is unsigned

### ISSUE THREAD

**Issue by zeha** [Orc/discount#151]
Hi,
In Debian we see test failures on our [build network](https://buildd.debian.org/status/package.php?p=discount), on some architectures. Failure log:
```
data corruption cases from Fernando Muñoz ............
id_000108_06
source:
	<p><!--
	    ?</>00000
diff:
	1,2c1,2
	< <p><p>&lt;!&ndash;
	<     </p>
	---
	> <p><p><!--
	>     ?</>00000</p>

tests/muñoz.t: 70 tests; 1 failed/69 passed
```

The same tests appear to work fine on amd64/i386 and some other archs -- the commonality of the failing architectures (arm64, arm*, powerpc, s390x) is that they all have `char` defined as `unsigned` (where on x86, `char` is `signed`).

I've tried debugging where this fails for a bit, but can't find anything obvious.

Thanks!

**Comment by Orc** [comment]
signed vs. unsigned is most likely part of the problem, but my processing of inline html comments is broken as well.   (`<p><!--` .... `>`  should become `<p>&lt;!&mdash; .... >` )

I will feast my eyes and see if I can fix the defect without introducing any massive hideous kludges.

**Comment by zeha** [comment]
I -think- the inline comment parsing gets confused by the 0xFF byte in there (represented as ?), but I couldn't confirm that.

**Comment by Orc** [comment]
It's deeper in than that.  If I try `markdown -t` with a string containing a 0x20, 0xff byte sequence everything past that sequence is lost (unless the 0x20, 0xff is at the start of the string) even if it's a string like `x `{0xff}`x`

I suspect it's in the `text()` processing loop.

**Comment by psychon** [comment]
I have no clue about the code base, no clue about discount and not much clue in general. I still searched for `ndash` (since it shows up in the failure) and looked at the surrounding code. Could someone test the following on a machine where `char` is unsigned?
```diff
diff --git a/generate.c b/generate.c
index c79861e..91ceff7 100644
--- a/generate.c
+++ b/generate.c
@@ -1119,9 +1119,13 @@ islike(MMIOT *f, char *s)
        len--;
     }
 
-    for (i=1; i < len; i++)
-       if (tolower(peek(f,i)) != s[i])
+    for (i=1; i < len; i++) {
+       int c = peek(f,i);
+       if (c == EOF)
            return 0;
+       if (tolower((unsigned char) c) != s[i])
+           return 0;
+    }
     return 1;
 }
 
```
The idea for the patch is:
- `peek` returns a `char` cast to `int` (or `EOF`, if beyond the end of the string)
- `man tolower` says about the argument `c`:

> If c is neither an unsigned char value nor EOF, the behavior of these functions is undefined.

- Thus, we need a cast to `unsigned char` on the call to `tolower` (and `EOF` needs special treatment).

The special value `0xff` should become `(int) -1` on architectures where `char` is signed. As far as I know, this is the value of `EOF`. Thus, I guess that The Real Bug(tm) is on architectures where char is signed, because here something treats the `0xff` as EOF.

`git grep tolower` says there are many other instances of the same pattern. Actually, all of these functions might cause a similar problem (copy&paste from `man isalpha`): isalnum,  isalpha,  isascii,  isblank,  iscntrl, isdigit, isgraph, islower, isprint, ispunct, isspace, isupper, isxdigit

For `isalnum` there is a wrapper `isthisalnum` which handles `EOF` specially, even though `isalnum` is documented so that `EOF` is a valid argument?

**Comment by Orc** [comment]
islike() is used for smartypants matching;  having a high bit extend there would be philosophically wrong, but would not damage anything because none of the smartypants patterns are anything other than 7 bit ascii.

I may have added the (c != EOF) check into isthisalnum because one of my build machines (possibly pell when I did most of my work on a Mastodon linux box?) had a libc that didn't deal properly with isalnum(EOF).    It's an inexpensive check (one compare+branch on any optimizing compiler worth it's salt; There are two function calls + other junk wrapped around it, so it's not as if optimizing it out -- or resurrecting pell so I have a Mastodon box again -- would give me any significant speedup :-( )

**Comment by psychon** [comment]
Ok, my previous comment might have been a bit confused. Sorry.

The issue turns out to be `(int)(signed char)0xff` and `EOF` having the same value and so this byte was mis-interpreted as the end of the input. See #152.

Side note: The bug is on architectures with signed char. Everything works correctly with unsigned char. So even the test is wrong!

**Comment by Orc** [comment]
I believe I found the place where 0xff was becoming eof & killing the universe, and I've pushed a patch up to correct that part (in generate.c, I explicitly cast T(Cstring)[i] to (unsigned char) in peek() and pull(), then to keep the stupid things from sign extending I've made peek() and pull() return unsigned int. (Ugh.   When I get around to properly unicoding this thing I can tell I'm going to be in for /weeks/ of excitement.)

htmlblock() [in markdown.c] is still broken (because flogetc() sign extends) but then again inline html comment processing is also broken so that needs to be visited before I push out an official bugfix release.
