### ISSUE TITLE
Support assuming the first 1st level heading as the page title?

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [Orc/discount#155]
Hi, I'm indirectly using Discount from [hamano/apache-mod-markdown: Markdown filter module for Apache HTTPD Server](https://github.com/hamano/apache-mod-markdown) and I'd like to make it assume that the 1st level heading is the page title (I don't want to use the Pandoc-style document headers as it will be rendered in other markdown viewers).  Is it technically possible?

**Comment by Orc** [comment]
Oh, yes, it's possible.   mod-markdown compiles the text first, then renders it later, so you can walk the document tree to find the first header.

Where mod_markdown.c calls `mkd_doc_title()`, you'd need to instead write a function that does

~~~~
Paragraph *
mkd_h1(Paragraph *p)
{
    Paragraph *found;

    while ( p ) {
        if ( p->typ == HDR && p->hnumber == 1 )
             return p;
       if ( p->down && (found = mkd_h1(p->down)) )
           return found;
        p = p->next;
    }
    return 0;
}

char *
mkd_h1_title(Document *doc, int flags)
{
    Paragraph *title;

    if (doc && (title = mkd_h1(doc->code)) ) {
          char *generated;
          int size;

          /* assert that a H1 header is one line long, so that's the only thing needed */
          size = mkd_line(T(title->text->text), S(title->text->text), &generated, flags);
          if ( size ) return generated;
    }
    return 0;
}
~~~~~

This first walks the document looking for a h1 paragraph, then renders it and returns it in a malloc()ed block.  It relys on the internal format of the MMIOT blob, so it would need to include markdown.h.  I'm guessing that mkd_markdown.c is based on mkd_xhtmlpage.c, but adapted to fit into an apache module, so you might be able to fit that code in instead of the call to mkd_doc_title()

**Comment by Lin-Buo-Ren** [comment]
Thanks!  That's far more than I ever expected.

**Comment by Orc** [comment]
Well, I'm kind of familiar with the internals of the code :-)

**Comment by somasis** [comment]
Not to hijack this issue (seemed like a fitting place to ask), but what are the chances this could be implemented as a feature in `theme`? It'd be really useful to me, I find the pandoc style metadata to be a little weird.

**Comment by Orc** [comment]
Possibly!  I'll check into it sometime in the next week or so (I've got the winter holidays now, plus I've a bicycle frame and a couple of racks I need to braze together before I can carve out a day to poke at this.

**Comment by somasis** [comment]
Great, thanks a lot, and have a good holiday :)

**Comment by Lin-Buo-Ren** [comment]
@somasis You're reading my mind :-)

**Comment by Orc** [comment]
I've pushed a patch that enables using the first h1 as the title in `theme` and `mkd2html`;  you need to enable it with the build option `--h1-title` (to `configure.sh`) and it appears to work with some of the minimal tests I've run.
