### ISSUE TITLE
markdown.c:571]: (style) Array index 'i' is used before limits check.

### ISSUE THREAD

**Issue by dcb314** [Orc/discount#169]
Source code is

        for (i=0; (T(p->text)[i] == T(p->text)[0]) && (i < S(p->text)-1)
                               && (i < 6); i++)

Suggest sanity check array index before use, not after.

**Comment by Orc** [comment]
Is there actually a defect here?

**Comment by dcb314** [comment]
Yes. A common enough failure mode that static analysers
get code added to detect it.

It's often good practice to look before leaping. Code that 
leaps and then looks will fail most tests of standard (ie good) practice.

**Comment by Orc** [comment]
No, I think you misunderstand.  Is there a defect *in discount* here?

**Comment by dcb314** [comment]
Still yes. I think we are going round in circles. Suggest either
fix the IMHO broken code or close the bug report WONTFIX.

**Comment by Orc** [comment]
Unless you can produce a defect, that code isn't broken (and I would be shocked if any defect popped up with that particular counter loop.)    Dumb machine analyzers are a useful tool, but their output isn't gospel; that version of the counter has been in production use for 7 years now (last changed when reddit found that really long # prefixes were being ingested and translated to <h{reallylargenumber}) and even if nobody in the world has used ETX headers since then my automated test suite would have fallen over if it was broken.)

So, yes, I'm afraid I'm going to close this and mark it as NOTEVENWRONG.
