### ISSUE TITLE
Footnotes don't act as block elements

### ISSUE THREAD

**Issue by somasis** [Orc/discount#183]
With `discount`, Footnotes have to exist on one line to be formatted properly. Attempting to make them contain paragraphs causes them to not give the expected result, a footnote with a paragraph. I don't know if that's intentional, but it seems like it should be mentioned if footnotes should only be allowed to be a single line...

At least, PHP Markdown Extra, from which Discount's footnotes documentation mentions appears to support this. <https://michelf.ca/projects/php-markdown/extra/#footnotes>

Example:

```markdown
Test[^1] footnote[^2] reference[^3].

[^1]: This works fine.
[^2]:
    This doesn't, it seems.

    How sad... This line should be part of footnote 2, but it's showing somewhere else. :(
[^3]: This doesn't. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do; then the footnote incorrectly ends after a newline
    eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
    veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo 
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

Output:

```html
<p>Test<sup id="fnref:1"><a href="#fn:1" rel="footnote">1</a></sup> footnote<sup id="fnref:2"><a href="#fn:2" rel="footnote">2</a></sup> reference<sup id="fnref:3"><a href="#fn:3" rel="footnote">3</a></sup>.</p>

<pre><code>This doesn't, it seems.

How sad... This line should be part of footnote 2, but it's showing somewhere else. :(
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo 
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</code></pre>
<div class="footnotes">
<hr/>
<ol>
<li id="fn:1">
<p>This works fine.<a href="#fnref:1" rev="footnote">&#8617;</a></p></li>
<li id="fn:2">
<p><a href="#fnref:2" rev="footnote">&#8617;</a></p></li>
<li id="fn:3">
<p>This doesn&rsquo;t. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do; then the footnote incorrectly ends after a newline<a href="#fnref:3" rev="footnote">&#8617;</a></p></li>
</ol>
</div>
```

**Comment by Orc** [comment]
Yes, that's how it's designed;  footnotes are implemented as a variant of the regular link.    I believe that's how the m-e implementation started (though I'm not sure) but it's obviously drifted to treating them as a special sort of nested block?

I will put on my pile of things to investigate -- it may just be a simple case of adding a feature flag and modifying the link target snarfer to treat link definitions starting with '^' as a block instead of one-or-two lines.

**Comment by Orc** [comment]
Okay, I've FINALLY done a workover on the code.  The branch extra_footnotes is the start of a version that doesn't do markdown extra-style footnotes as just one line.

One question:  does the m-e one do multiple paragraphs in footnotes (sfx: tearing hear, crying WHHHHYYYYYYY!) and just hoover up everything until it finds a line that's not indented at all?

**Comment by Orc** [comment]
Okay, so it looks like m-e does the "accepts full markdown" behavior in footnotes (like a quoted block) so I've implemented that behavior and pushed it to the extra_footnotes branch.   I've not done any cleaning of the bits of glue code I needed to write, nor are there any test cases yet (and the existing m-e footnote test cases are broken due to the tweaks I did to formatting so it wouldn't do couple `<p>` blocking for multi-paragraph footnotes) but the small pile of test cases I wrote to validate it run w/o it either exploding, producing wrong output, or failing to garbage collect.

**Comment by Orc** [comment]
First round of tests are finished, so I've merged this branch back into the baseline.   If I can't provoke a bug in the next couple of days I'll close out this issue, so if you can test it out please do so and let me know about anything that doesn't seem to be working properly.

**Comment by somasis** [comment]
Looks like it works just fine in my usage, I haven't noticed anything that looks out of place. Thanks a lot :+1:

**Comment by Orc** [comment]
Excellent!
