### ISSUE TITLE
A memory leak appear when put tests/misc.t as the input of the executable file: mkd2html

### ISSUE THREAD

**Issue by fCorleone** [Orc/discount#188]
=================================================================
==29911==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 19 byte(s) in 1 object(s) allocated from:
    #0 0x7f52b551f602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x402398 in main /home/ubuntu/mfc_fuzz/discount/mkd2html.c:140

SUMMARY: AddressSanitizer: 19 byte(s) leaked in 1 allocation(s).

That information appeared when I put the test file tests/misc.t  as the input of mkd2html.

**Comment by Orc** [comment]
Yes, that's because mkd2html allocates a buffer for the destination html file, but leaves it up to the runtime to clean up when the program finishes.    It's a simple filter program, so it doesn't care about gc (and tbh neither do I; discount itself is pretty paranoid about gc, but wrapper scripts don't need to be.)

But if you'd like to patch it I'll the patch!

**Comment by fCorleone** [comment]
OK, Thank you for your reply.

**Comment by Crypto-Anarchist** [comment]
Take a look to this comment: https://github.com/Orc/discount/issues/189#issuecomment-397880817

**Comment by Orc** [comment]
Are you drunk?  Because really that's the only explanation I can see for this non-sequitur.
