### ISSUE TITLE
More human-friendly anchors with the toc option

### ISSUE THREAD

**Issue by Lekensteyn** [Orc/discount#199]
The current `toc` option produces quite ugly anchors:
```sh
echo '# PS/2 (my-interface)' | markdown -f toc
```

This currently produces: `PS-2f-2--28-my-2d-interface-29-`,
while I would have liked: `ps2-my-interface` (compatible with Github Flavored Markdown).

I was hoping to have anchors that match the expectations from
https://github.com/mzlogin/vim-markdown-toc/blob/master/ftplugin/markdown.vim#L143

**Comment by Orc** [comment]
I'll accept a patch that (with #ifdefs so it can be feature-enabled in configure.sh -- I'm out of flag bits for a 32 bit flag_t) reworks mkd_string_to_anchor to generate crunched tags like that.

**Comment by Lekensteyn** [comment]
It should probably not be a compile-time setting but a runtime one (if you want to make it configurable) to avoid different "markdown" binaries with different behavior.

If you want to make it runtime configurable, have you thought of ways to extend the current API?

**Comment by Orc** [comment]
Well, if you want it _now_, I'm afraid it has to be done with compile-time ifdefs.

**Comment by Lekensteyn** [comment]
There is no hurry, there is time to engineer a correct solution:

At the moment I am using GNU sed for postprocessing (lowercase everything, preserve `-` and strip all others):

    sed '/^<a name=/{s/[A-Z]/\L&/g;s/-2d-/-/g;s/-[0-9a-f][0-9a-f]-//g}'

**Comment by Orc** [comment]
Okay, several months later I revisited this.  Still no expanded flags, but I've implemented it by adding a callback function for anchor formatting (`mkd_e_anchor(Document*,function(char*,void*))`, where `function` takes the raw id tag to be, which it mangles to the desired format and returns) and putting a new flag -- `-x` -- into the markdown program which mangles ids into the github form you described (modulo extended unicode characters, because discount currently treats the input as a bytestream instead of a utf-8 encoded character stream.)

It's on top of stack, and passes my test suite (which has not been modified to test the `-x` option for the markdown program.)

**Comment by Orc** [comment]
That code hasn't messily exploded for me, so I'm gonna set this issue as closed because, at least in _my_ village, it works :-)
