### ISSUE TITLE
Generate table of contents anywhere in the document

### ISSUE THREAD

**Issue by timakro** [Orc/discount#226]
I don't see a way to add a table of contents when processing a markdown file with the `theme` binary. 

I'd suggest adding `[TOC]` to generate the table of contents [like Python-Markdown does it](https://python-markdown.github.io/extensions/toc/). This would also allow you to place the table of contents at any position in the document with the `markdown` binary whereas with the `-T` flag it is always placed at the beginning.

**Comment by Orc** [comment]
There isn't one.   I'd welcome a patch to do it, but I'm working out some misfeatures in the existing toc code and don't want to spread my attention too much.

Python-markdown uses `[TOC]`, which puts magic into the description part of a link?  Ew.   (There's a reason I do pseudo-protocols for stuff like that!)

**Comment by Orc** [comment]
After much dysphoria (and the traditional remedy) I've revisited this.    I don't think I want to change this behavior myself, but I'd **happily** accept a patch for the markdown -- or theme -- program itself (in main.c) that lets you put the toc anywhere.    Theme might be a better bet, because it already has pseudo-tag support and you could do something like `<?theme toc?>` to stuff the toc in where you want.
