### ISSUE TITLE
# inside <Code>

### ISSUE THREAD

**Issue by CalebCDE** [Orc/discount#284]
Hi.

I have this issue when convert to html

If i have a <Code> block (bash) with comments (#EOF in my case)

It convert EOF to a title :)

**Comment by Orc** [comment]
Can you show me a sample that causes discount to fail?

**Comment by CalebCDE** [comment]
Hi. Sure :-)

<code>#!bin/bash
data=$(BeInput "Insert your name")
echo "Your name is" $data
#EOF</code>

is the code

<p><code>#!bin/bash
data=$(BeInput &ldquo;Insert your name&rdquo;)
echo &ldquo;Your name is&rdquo; $data</p>

<h1>EOF</code></h1>

is the output

**Comment by Orc** [comment]
Alas, that's the output that's supposed to happen according to standard (John Gruber's) markdown.   If you put that code into the [markdown dingus](https://daringfireball.net/projects/markdown/dingus) that's what you'll see.  What's happening is the parser is breaking the code into two paragraphs:

    <code>#!bin/bash
    data=$(BeInput "Insert your name")
    echo "Your name is" $data

and

    #EOF</code>

and then it doesn't process either as paragraphs containing code sections.

This is a behavior I cannot change while keeping discount markdown compatable, sorry :-(

Have you considered using either fenced code (if you're calling discount as a library, set the MKD_FENCEDCODE flag, and if you're using the `markdown` sample program giving it the argument `-ffencedcode` or the traditional method of doing tab indentation?

(fenced code):

    ~~~~
    #!bin/bash
    data=$(BeInput "Insert your name")
    echo "Your name is" $data
    #EOF
    ~~~~

(tab indentation -- the \<tab> markings signify either 4 space indent or a tab character)

~~~~
<tab>#!bin/bash
<tab>data=$(BeInput "Insert your name")
<tab>echo "Your name is" $data
<tab>#EOF
~~~~

(a fast shortcut would be to merely escape the `#` -- instead of typing `#EOF`, do `\#EOF`, but it's just easier to wrap everything in a codeblock instead of needing to remember to do back and escape all the weird characters on column 0)
