### ISSUE TITLE
MKD_TOC should respect multi byte chars.

### ISSUE THREAD

**Issue by tokuhirom** [Orc/discount#89]
MKD_TOC is not useful for multi byte chars users. Because it replaces multi byte char to '.'.
I suggest to use uri escaping instead.

**Comment by Orc** [comment]
After many many years I think I've got a fix for it. Instead of blindly replacing out of namespace characters I encode them to hex sequences (and urlencodedanchor is in the throes of being converted to html5anchor, which uses the html5 namespace and allows most nonascii characters through untouched.)

Check out version 2.2.2 and tell me if it works for you?
